import { Translations } from './types';

export const TRANSLATIONS: Translations = {
    es: {
        nav_tools: "HERRAMIENTAS",
        nav_calc: "Calculadora de Tuberías",
        nav_gears: "Cálculo de Engranaje",
        nav_cad: "CAD VIEWER",
        nav_works: "TRABAJOS",
        hero_title: "Proyectos de Ingeniería",
        hero_desc: "Simplificamos procesos técnicos con precisión. Acceda a nuestra suite de herramientas desde el menú superior.",
        contact_title: "Contacto Directo",
        contact_desc: "¿Tiene alguna consulta técnica, sugerencia sobre nuestras herramientas o requiere asistencia personalizada? Utilice el formulario para enviar un mensaje directo a nuestra administración.",
        input_email: "Su Correo Electrónico",
        input_msg: "Escriba su mensaje...",
        btn_send: "ENVIAR",
        footer_rights: "© 2024 DESPUX. Todos los derechos reservados.",
        footer_dev: "Desarrollado y mantenido por Marcos Despujos.",
        work_tag: "INGENIERÍA ESTRUCTURAL",
        work_title: "Análisis de Integridad Estructural",
        work_desc: "Implementación de algoritmos avanzados para el cálculo de resistencia de materiales en infraestructuras críticas. Este proyecto utiliza modelado 3D y simulaciones de estrés en tiempo real para predecir puntos de fallo y optimizar el mantenimiento preventivo.",
        work_btn: "VER DETALLES",
        work2_tag: "DISEÑO MECÁNICO",
        work2_title: "Ciclón Separador Inoxidable",
        work2_desc: "Diseño y fabricación de un sistema de separación ciclónica en acero inoxidable para ambientes corrosivos. Este módulo permite la filtración eficiente de partículas en suspensión para procesos industriales de alta pureza."
    },
    en: {
        nav_tools: "TOOLS",
        nav_calc: "Pipe Calculator",
        nav_gears: "Gear Calculation",
        nav_cad: "CAD Viewer",
        nav_works: "PROJECTS",
        hero_title: "Engineering Projects",
        hero_desc: "We simplify technical processes with precision. Access our suite of tools from the top menu.",
        contact_title: "Direct Contact",
        contact_desc: "Do you have a technical query, suggestion about our tools, or require personalized assistance? Use the form to send a direct message to our administration.",
        input_email: "Your Email Address",
        input_msg: "Write your message...",
        btn_send: "SEND",
        footer_rights: "© 2024 DESPUX. All rights reserved.",
        footer_dev: "Developed and maintained by Marcos Despujos.",
        work_tag: "STRUCTURAL ENGINEERING",
        work_title: "Structural Integrity Analysis",
        work_desc: "Implementation of advanced algorithms for calculating material resistance in critical infrastructure. This project uses 3D modeling and real-time stress simulations to predict failure points and optimize preventive maintenance.",
        work_btn: "VIEW DETAILS",
        work2_tag: "MECHANICAL DESIGN",
        work2_title: "Stainless Cyclone Separator",
        work2_desc: "Design and manufacture of a stainless steel cyclonic separation system for corrosive environments. This module enables efficient filtration of suspended particles for high-purity industrial processes."
    },
    de: {
        nav_tools: "WERKZEUGE",
        nav_calc: "Rohrrechner",
        nav_gears: "Zahnradberechnung",
        nav_cad: "CAD-Betrachter",
        nav_works: "PROJEKTE",
        hero_title: "Ingenieurprojekte",
        hero_desc: "Wir vereinfachen technische Prozesse mit Präzision. Greifen Sie über das obere Menü auf unsere Tool-Suite zu.",
        contact_title: "Direkter Kontakt",
        contact_desc: "Haben Sie eine technische Frage, einen Vorschlag zu unseren Tools oder benötigen Sie persönliche Unterstützung? Nutzen Sie das Formular, um eine direkte Nachricht an unsere Verwaltung.",
        input_email: "Ihre E-Mail-Adresse",
        input_msg: "Schreiben Sie Ihre Nachricht...",
        btn_send: "SENDEN",
        footer_rights: "© 2024 DESPUX. Alle Rechte vorbehalten.",
        footer_dev: "Entwickelt und gepflegt von Marcos Despujos.",
        work_tag: "BAUINGENIEURWESEN",
        work_title: "Analyse der Strukturintegrität",
        work_desc: "Implementierung fortschrittlicher Algorithmen zur Berechnung der Materialbeständigkeit in kritischen Infrastrukturen. Dieses Projekt nutzt 3D-Modellierung und Echtzeit-Belastungssimulationen, um Fehlerstellen vorherzusagen.",
        work_btn: "DETAILS ANZEIGEN",
        work2_tag: "MECHANISCHES DESIGN",
        work2_title: "Edelstahl-Zyklonabscheider",
        work2_desc: "Konstruktion und Fertigung eines Zyklonabscheidesystems aus Edelstahl für korrosive Umgebungen. Dieses Modul ermöglicht die effiziente Filtration von Schwebeteilchen für hochreine industrielle Prozesse."
    }
};